<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2016 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

$loadProducts = (int)Mage::helper('googletagmanager')->getConfigValue('category_products');
if ($loadProducts > 0) {
    $productCollection = $this->getProductCollection();
}

if ($this->isEnabled()) {
    $category = $this->getCategory();
    if (!empty($category) && $category->getId() > 0) {
        $this->addAttribute('categoryId', $category->getId());
        $this->addAttribute('categoryName', $this->quoteEscape($category->getName()));
    }

    if (!empty($productCollection)) {
        $this->addAttribute('categorySize', $productCollection->getSize());
        $categoryProducts = array();

        $i = 0;
        foreach ($productCollection as $product) {

            if ($i > $loadProducts) {
                break;
            }

            $taxCalculation = Mage::getModel('tax/calculation');
            $request = $taxCalculation->getRateRequest(null, null, null, $store);
            $taxClassId = $product->getTaxClassId();
            $taxpercent = $taxCalculation->getRate($request->setProductClassId($taxClassId));

            $price = $product->getPrice();
            $specialPrice = $product->getSpecialprice();
            if (($specialPrice > 0) && ($specialPrice < $price)) {
                $price = $specialPrice;
            }
            $tax = ($price / (100 + $taxpercent)) * $taxpercent;
            $gender = Mage::getModel('catalog/resource_eav_attribute')->loadByCode(Mage_Catalog_Model_Product::ENTITY, 'gender')->getSource()->getOptionText($product->getGender());

            $categoryProduct = array();
            $categoryProduct['id'] = $product->getId();
            $categoryProduct['name'] = $this->quoteEscape($product->getName());
            $categoryProduct['sku'] = $this->quoteEscape($product->getSku());
            $categoryProduct['price'] = $price;
            $categoryProduct['priceexcludingtax'] = number_format($price - $tax, 2);
            $categoryProduct['tax'] = number_format($tax, 2);
            $categoryProduct['taxrate'] = $taxpercent;
            $categoryProduct['gender'] = $gender;

            if (!empty($category) && $category->getId() > 0) {
                $categoryProduct['category'] = $this->quoteEscape($category->getName());
            }

            $categoryProduct['position'] = $i;

            $categoryProducts[] = $categoryProduct;
            $i++;
        }

        $this->addAttribute('categoryProducts', $categoryProducts);
        $this->getModuleHelper()->addEcommerceData('impressions', $categoryProducts);
    }
}
