<?php
/**
 * GoogleTagManager plugin for Magento 
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<?php if($this->isEnabled()) : ?>
<?php $category = $this->getCategory(); ?>
<?php if(!empty($category) && $category->getId() > 0) : ?>
    <?php $this->addAttribute('categoryId', $category->getId()); ?>
    <?php $this->addAttribute('categoryName', $category->getName()); ?>
<?php endif; ?>
<?php endif; ?>
