<?php
/**
 * GoogleTagManager plugin for Magento 
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<?php if($this->isEnabled()) : ?>

<noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $this->getId(); ?>"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<?php $childScript = $this->getChildScript(); ?>
<?php if(!empty($childScript)) : ?>
<script>
<?php if($this->hasAttributes()) : ?>
dataLayer = [<?php echo $this->getAttributesAsJson(); ?>];
<?php endif; ?>
<?php echo $childScript; ?>
</script>
<?php endif; ?>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push(
{'gtm.start': new Date().getTime(),event:'gtm.js'}
);var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','<?php echo $this->getId(); ?>');</script>
<?php endif; ?>
