<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<?php if ($this->isEnabled()) : ?>
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=<?= $this->getId(); ?>" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <?php $childScript = $this->getChildScript(); ?>
    <script>
    <?php if (!empty($childScript)) : ?>
            <?php if($this->hasAttributes()) : ?>
            dataLayer = [<?= $this->getAttributesAsJson(); ?>];
            <?php endif; ?>
            <?= $childScript; ?>
    <?php endif; ?>
    (function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
            var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src = '//www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', '<?= $this->getId(); ?>');
    </script>
<?php endif; ?>