<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2019 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

/** @var Mage_Core_Block_Template $this */
/** @var Yireo_GoogleTagManager_Helper_Data $helper */
$helper = $this->helper('googletagmanager');
?>

<?php if ($helper->isDebug()) : ?>
    <pre id="googletagmanager-debug"></pre>
    <script>
        console.log(window.dataLayer);
        document.getElementById('googletagmanager-debug').innerHTML = JSON.stringify(window.dataLayer);
    </script>
<style>
    #googletagmanager-debug {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        z-index: 2;
        background-color: white;
        border-top: 1px solid #ddd;
        padding: 4px;
        word-wrap: break-word;
        white-space: pre-wrap;
    }
</style>
<?php endif; ?>
