<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2017 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

/** @var Yireo_GoogleTagManager_Block_Head $block */

?>
<?php if ($this->isEnabled()) : ?>
    <script>
        var dataLayer = [];
        (function (w, d, s, l, i) {
            if (i == '') { return console.log('No GTM ID provided'); }
            w[l] = w[l] || [];
            w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
            if (i == 'DEBUG') return console.log(w[l]);
            var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            var environment = '<?= $this->getEnvironment(); ?>';
            j.async = true;
            j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl + environment;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', '<?= $this->getId(); ?>');
    </script>
<?php endif; ?>
