<?php
/**
 * GoogleTagManager plugin for Magento 
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<?php if($this->isEnabled()) : ?>
<?php $order = $this->getOrder(); ?>
<?php if(!empty($order) && $order->getId() > 0) : ?>
    <?php $this->addAttribute('transactionId', $order->getIncrementId()); ?>
    <?php $this->addAttribute('transactionAffiliation', Mage::app()->getWebsite()->getName()); ?>
    <?php $this->addAttribute('transactionTotal', (float)$order->getGrandTotal()); ?>
    <?php $this->addAttribute('transactionTax', $order->getGrandTotal() - $order->getSubtotal()); ?>
    <?php $this->addAttribute('transactionShipping', (float)$order->getShippingAmount()); ?>
    <?php $this->addAttribute('transactionProducts', $this->getItemsAsJson()); ?>
<?php endif; ?>
<?php endif; ?>
