<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2017 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

/**
 * To use this code, add the following line to your PHTML templates:
 * <?php $gtm = Mage::helper('googletagmanager/script'); ?>
 * <?php echo $gtm->onAddToCart($_product); ?>
 */

if ( !$this->isEnabled() ) {
    return;
}

/** @var Mage_Catalog_Model_Product $product */
$product = $this->getProduct();
$data = array(
    'event' => 'addToCart',
    'ecommerce' => array(
        'currencyCode' => $this->getScriptHelper()->getCurrencyCode(),
        'add' => array(
            'products' => array(
                array(
                    'name' => $this->quoteEscape(str_replace("'","", $product->getName())),
                    'id' => $product->getId(),
                    'price' => $this->formatPrice($product->getPrice()),
                    'quantity' => 1,
                )
            )
        )
    ),
);
?>
dataLayer.push(<?php echo $this->jsonEncode($data); ?>);
