<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2016 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */
/**
 * To use this code, add the following line to your PHTML templates:
 * <?php $gtm = Mage::helper('googletagmanager/script'); ?>
 * <?php echo $gtm->onRemoveAll($_product); ?>
 */
if ( !$this->isEnabled() ) {
    return;
}
/** @var Mage_Catalog_Model_Product $product */
$product = $this->getProduct();
$qty = $product->getQty();

$data = array(
    'event' => 'removeFromCart',
    'ecommerce' => array(
        'currencyCode' => $this->getScriptHelper()->getCurrencyCode(),
        'remove' => array(
            'products' => array(
                array(
                    'name' => $this->quoteEscape(str_replace("'", "", $product->getName())),
                    'id' => $product->getId(),
                    'price' => $this->formatPrice($product->getPrice()) * $qty,
                    'quantity' => $qty,
                )
            )
        )
    ),
);
?>
dataLayer.push(<?php echo $this->jsonEncode($data); ?>);
