<?php
/**
 * GoogleTagManager plugin for Magento 
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<?php if($this->isEnabled()) : ?>
<?php $quote = $this->getQuote(); ?>
<?php if(!empty($quote) && $quote->getId() > 0) : ?>
    <?php $this->setAttribute('transactionId', $quote->getId()); ?>
    <?php $this->setAttribute('transactionAffiliation', Mage::app()->getWebsite()->getName()); ?>
    <?php $this->setAttribute('transactionTotal', $quote->getGrandTotal()); ?>
    <?php $this->setAttribute('transactionTax', $quote->getGrandTotal() - $quote->getSubtotal()); ?>
    <?php $this->setAttribute('transactionProducts', $this->getItemsAsJson()); ?>
<?php endif; ?>
<?php endif; ?>
