<?php
/**
 * GoogleTagManager plugin for Magento 
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<?php if($this->isEnabled()) : ?>
<script>
<?php $quote = $this->getQuote(); ?>
<?php if(!empty($quote) && $quote->getId() > 0) : ?>
dataLayer = [{
    'transactionId': '<?php echo $quote->getId(); ?>',
    'transactionAffiliation': '<?php echo Mage::app()->getWebsite()->getName(); ?>',
    'transactionTotal': <?php echo $quote->getGrandTotal(); ?>,
    'transactionTax': <?php echo $quote->getGrandTotal() - $quote->getSubtotal(); ?>,
    'transactionProducts': <?php echo $this->getItemsAsJson(); ?>
}];
<?php endif; ?>
</script>
<?php endif; ?>
