<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2017 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

/** @var Yireo_GoogleTagManager_Block_Order $block */

if ($this->isEnabled()) {
    $order = $this->getOrder();
    if (!empty($order) && $order->getId() > 0) {
        $this->addAttribute('transactionEntity', 'ORDER');
        $this->addAttribute('transactionId', $order->getIncrementId());
        $this->addAttribute('transactionDate', $order->getCreatedAt());
        $this->addAttribute('transactionAffiliation', $this->quoteEscape(Mage::app()->getWebsite()->getName()));
        $this->addAttribute('transactionTotal', (float)$order->getGrandTotal());
        $this->addAttribute('transactionSubtotal', (float)$order->getSubtotal());
        $this->addAttribute('transactionTax', $order->getGrandTotal() - $order->getShippingAmount() - $order->getSubtotal());
        $this->addAttribute('transactionShipping', (float)$order->getShippingAmount());
        $this->addAttribute('transactionPayment', $this->quoteEscape($order->getPayment()->getMethodInstance()->getTitle()));
        $this->addAttribute('transactionCurrency', Mage::app()->getStore()->getBaseCurrencyCode());
        $this->addAttribute('transactionPromoCode', $this->quoteEscape($order->getCouponCode()));
        $this->addAttribute('transactionProducts', $this->getItems());
    }
}
