<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2016 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

/** @var Yireo_GoogleTagManager_Block_Product $this */
/** @var Mage_Catalog_Model_Product $product */
$product = $this->getProduct();

if (!$this->isEnabled() || !$product || !$product->getId()) {
    return '';
}

$priceModel = $this->getPriceModel()->setProduct($product);

$this->addAttribute('productId', $product->getId());
$this->addAttribute('productName', $this->quoteEscape($product->getName()));
$this->addAttribute('productSku', $this->quoteEscape($product->getSku()));
$this->addAttribute('productPrice', $this->formatPrice($priceModel->getPriceInclTax()));
$this->addAttribute('productPriceExcludingTax', $this->formatPrice($priceModel->getPriceExclTax()));
$this->addAttribute('productTax', $this->formatPrice($priceModel->getTax()));
$this->addAttribute('productTaxRate', $priceModel->getTaxRate());
$this->addAttribute('productGender', $this->getGender());
$this->addAttribute('productType', $this->getType());
$this->addAttribute('productBrand', $this->quoteEscape($this->getProductAttributeText($product, 'manufacturer')));

$children = array();
$child = array();
if ($product->isSuper()) {
    $childProducts = $this->getChildProducts($product);
    foreach ($childProducts as $childProduct) {
        $priceModel->setChildProduct($childProduct);
        $child['name'] = $childProduct->getName();
        $child['id'] = $childProduct->getId();
        $child['price'] = $this->formatPrice($priceModel->getPriceInclTax());
        $child['priceexcludingtax'] = $this->formatPrice($priceModel->getPriceExclTax());
        $child['sku'] = $childProduct->getSku();
        array_push($children, $child);
    }

    $this->addAttribute('productChildren', $children);
}

$category = $product->getCategory();
$categoryName = (is_object($category)) ? $this->quoteEscape($category->getName()) : '';

$detail = array();

if (!empty($categoryName)) {
    $detail['actionField'] = array('list' => $categoryName);
}

$productData = array(
    'id' => $product->getId(),
    'name' => $this->quoteEscape($product->getName()),
    'sku' => $product->getSku(),
    'price' => $this->formatPrice($priceModel->getPriceInclTax()),
    'priceexcludingtax' => $this->formatPrice($priceModel->getPriceExclTax()),
    'tax' => $this->formatPrice($priceModel->getTax()),
    'taxrate' => $priceModel->getTaxRate(),
    'brand' => $this->quoteEscape($this->getProductAttributeText($product, 'manufacturer')),
    'gender' => $this->getGender(),
    'category' => $categoryName,
    'children' => $children,
);

$detail['products'] = array($this->cleanData($productData));
$this->getScriptHelper()->addEcommerceData('detail', $detail);
