<?php
/**
 * GoogleTagManager plugin for Magento 
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2017 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

/** @var Yireo_GoogleTagManager_Block_Quote $block */
$quote = $this->getQuote();

if($this->isEnabled() && $quote) {
    $totals = $quote->getTotals();
    $tax = (isset($totals['tax'])) ? $totals['tax']->getValue() : '';

    if(!empty($quote) && $quote->getId() > 0) { 
        $this->addAttribute('transactionEntity', 'QUOTE'); 
        $this->addAttribute('transactionId', $quote->getId()); 
        $this->addAttribute('transactionId', $quote->getId()); 
        $this->addAttribute('transactionAffiliation', $this->quoteEscape(Mage::app()->getWebsite()->getName())); 
        $this->addAttribute('transactionTotal', (float)$quote->getGrandTotal()); 
        $this->addAttribute('transactionTax', $quote->getGrandTotal() - $quote->getShippingAmount() - $quote->getSubtotal()); 
        $this->addAttribute('transactionProducts', $this->getItemsAsArray());
    } 
} 
